### ISSUE TITLE
node_modules w repo

### ISSUE THREAD

**Issue by patwork** [zuzozuo/node_school_project#1]
Oh noes!

Nie dodajemy katalogu "node_modules" do repo! Nie ma sensu ładować dziesiątek megabajtów cudzych bibliotek na swoje konto githuba. Zamiast tego trzeba NAJPIERW przy pomocy komendy:

`npm init
`

utworzyć plik projektu package.json, w którym NASTĘPNIE przy pomocy komendy:

`npm install --save nazwapaczki1 nazwapaczki2 nazwapaczki3 itd
`

zapisze się lista wszystkich wymaganych bibliotek z npm.

Jeszcze PRZED commitem do gita w katalogu projektu dodajemy plik ".gitignore", w którym zapisane są nazwy plików/katalogów, które mają się NIE dodawać do repo.

Przykład dla node (w linii 36 jest wykluczanie katalogu node_modules):
https://github.com/github/gitignore/blob/master/Node.gitignore

Dzięki powyższym działaniom, w repozytorium zapisują się wyłącznie pliki projektu plus informacja o wymaganych bibliotekach. Jeżeli ktoś będzie chciał pobrać i uruchomić projekt, wystarczy że wykona trzy polenia:

```
git clone https://github.com/zuzozuo/node_school_project.git
cd node_school_project/
npm install
```

PS. przykład z mojego kill-the-cat:
https://github.com/patwork/kill-the-cat/blob/master/package.json
https://github.com/patwork/kill-the-cat/blob/master/.gitignore

**Comment by zuzozuo** [comment]
Mam problem z nazwą paczki. Cały czas zwraca mi błąd:  _"Sorry, name can only contain URL-friendly characters."_ , rozglądałam się na stack'ach i dokumentacji ale nie za bardzo mi to pomogło ;/

**Comment by patwork** [comment]
https://github.com/npm/validate-npm-package-name#naming-rules

Nie wiem jaką nazwę wpisujesz, ale najlepiej będzie się ograniczyć tylko do małych liter i minusów albo podkreśleń jako odstępów. Bez polskich liter!

Zresztą jak odpalisz npm init w katalogu z pobranym repo z githuba to wystarczy naciskać enter i wygeneruje się całkiem sensowny plik.

```
package name: (node_school_project) 
version: (1.0.0) 
description: 
entry point: (server.js) 
test command: 
git repository: (https://github.com/zuzozuo/node_school_project.git) 
keywords: 
author: 
license: (ISC) 
```

**Comment by zuzozuo** [comment]
Wszystko już śmiga! B)
